#server:
#  port: 9003
#
#
#spring:
#  application:
#    name: WINERY-SERVICE
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://app0:8761/eureka/
#  instance:
#    hostname: app0
#
