server:
  port: 9001


spring:
  application:
    name: REVIEW-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://app0:8761/eureka/
  instance:
    hostname: app0

